from __future__ import annotations

from inercia.db.manager import (
    create_proposal,
    count_submitted_today,
    get_connection,
    get_connects_spent_today,
    get_job,
    get_job_by_upwork_id,
    get_proposal,
    get_session_value,
    init_db,
    list_jobs_by_status,
    list_proposals_by_status,
    log_connects,
    set_session_value,
    update_job_roi,
    update_job_status,
    update_proposal_status,
    upsert_job,
)
from inercia.db.models import ConnectsLogRow, JobRow, ProposalRow, SessionRow

__all__ = [
    "ConnectsLogRow",
    "JobRow",
    "ProposalRow",
    "SessionRow",
    "create_proposal",
    "count_submitted_today",
    "get_connection",
    "get_connects_spent_today",
    "get_job",
    "get_job_by_upwork_id",
    "get_proposal",
    "get_session_value",
    "init_db",
    "list_jobs_by_status",
    "list_proposals_by_status",
    "log_connects",
    "set_session_value",
    "update_job_roi",
    "update_job_status",
    "update_proposal_status",
    "upsert_job",
]
